### ISSUE TITLE
Cannot select plan on Safari (iPhone)

### ISSUE THREAD

**Issue by gytiskin** [ProtonVPN/proton-vpn-settings#142]
Plan table is cut off and user is not able to scroll down and update plans. 

![IMG_0229 (1)](https://user-images.githubusercontent.com/54268246/64408376-43ecbd80-d08f-11e9-8575-99ecce54967c.JPG)

**Comment by nico3333fr** [comment]
After having tested on an iPhone SE, the problem seems to come from container with horizontal scrolling.

If you try to scroll on the left of the plans, you scroll on the main page, otherwise, you're stucked into the container with horizontal scroll. It's easy to do when you know, but impossible to guess.

I don't see any better solution than a real mobile adaptation, without any horizontal scroll :-\

**Comment by RandomAdversary** [comment]
@nico3333fr  The easy fix would be to add left & right arrows, the same way we do with ProtonMail.

![image](https://user-images.githubusercontent.com/11393457/64469954-75bb5e00-d13b-11e9-8daf-fdcd48096a07.png)
![image](https://user-images.githubusercontent.com/11393457/64469966-984d7700-d13b-11e9-8dbd-2ac6b01a25c7.png)

**Comment by kylekatarnls** [comment]
It seems like https://protonvpn.com/pricing now uses responsive columns which work fine on Safari iOS too.

Do you still need help here?

**Comment by gytiskin** [comment]
Looks good now, closing.
